server:
  port: 2222

spring:
  redis:
    timeout: 6000ms
    password: '123456'
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 8.129.178.38:6379
        - 8.129.178.38:6380
        - 8.129.178.38:6381
        - 8.129.178.38:6382
        - 8.129.178.38:6383
        - 8.129.178.38:6384
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: 100ms # 连接池最大阻塞等待时间（使用负值表示没有限制）


  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://8.129.178.38:3306/redis_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    filters: stat,wall,log4j     #druid监控配置
    dbcp2:
        min-idle: 5         #数据库连接池的最小维持连接数
        initial-size: 5     #初始化提供的连接数
        max-total: 5          #最大的连接数
        max-wait-millis: 200        #等待连接获取的最大超时时间

# dubbo producer config
  dubbo:
    application:
      name: producer-pd
    registry:
#      address: zookeeper://8.129.178.38:2181,8.129.178.38:2182,8.129.178.38:2183
      registries[0]:
        address: zookeeper://8.129.178.38:2181
      registries[1]:
        address: zookeeper://8.129.178.38:2182
      registries[2]:
        address: zookeeper://8.129.178.38:2183
    protocol:
      name: dubbo
      port: 20882
    scan: com.producer.service
