server:
  port: 2222

spring:
  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 8.129.178.38:6379
        - 8.129.178.38:6380
        - 8.129.178.38:6381
        - 8.129.178.38:6382
        - 8.129.178.38:6383
        - 8.129.178.38:6384
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: 100ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
